### ISSUE TITLE
Skipped tests are reported as failures

### ISSUE THREAD

**Issue by ghost** [martinmcwhorter/karma-nunit2-reporter#1]
Hi Martin, tests marked to be skipped are reported as failures right now.
This means that any build with a skipped test will fail.

We're using mocha to run tests. When we do `xit()` or `xdescribe()` the tests are skipped, but our build fails because it has multiple 'failures' being reported.

I'm about to raise a PR for this, which should report skipped tests as successful.
Does that sound like the right approach to you?

**Comment by ghost** [comment]
Pull request is now here: https://github.com/martinmcwhorter/karma-nunit2-reporter/pull/2

Are you happy with the change?

**Comment by martinmcwhorter** [comment]
I merged in your changes. I will update here when I publish to NPM. Ill try to merge pull requests quicker in the future.

**Comment by ghost** [comment]
That's great. Thanks Martin. Please let us know when you push to NPM, and I can remove our project's dependency on my fork.
Cheers!

**Comment by martinmcwhorter** [comment]
Version 0.3.0 has been pushed to npm

**Comment by ghost** [comment]
<3
Great, thanks!

**Comment by ghost** [comment]
Hey, I've just noticed readme.md's "package.json" example is out of date, listing version ~0.1.
Should this read `"^0.3"`? or perhaps `"0.X" // Latest version here`, or perhaps just recommend `install --save-dev` is used and give no example that needs a version?
